### ISSUE TITLE
Lotto System

### ISSUE THREAD

**Issue by KfzMatze45** [emre1702/Ultimate#2]
Das Lotto System geht nicht.

WARNING: [gamemodes]/[ultimate]/ultimate/fun/lotto/lotto_server.lua:2: Bad usage @ 'fileOpen' [unable to load file 'vio_stored_files/lotto/jackpot.vio']
WARNING: [gamemodes]/[ultimate]/ultimate/fun/lotto/lotto_server.lua:3: Bad argument @ 'fileGetSize' [Expected scriptfile at argument 1, got boolean]
WARNING: [gamemodes]/[ultimate]/ultimate/fun/lotto/lotto_server.lua:4: Bad argument @ 'fileRead' [Expected scriptfile at argument 1, got boolean]
WARNING: [gamemodes]/[ultimate]/ultimate/fun/lotto/lotto_server.lua:5: Bad argument @ 'fileClose' [Expected scriptfile at argument 1, got boolean]

ERROR: [gamemodes]/[ultimate]/ultimate/script.lua:10: attempt to concatenate global 'lottoJackpot' (a nil value)
ERROR: [gamemodes]/[ultimate]/ultimate/fun/lotto/lotto_server.lua:69: attempt to perform arithmetic on global 'lottoJackpot' (a nil value)

**Comment by emre1702** [comment]
Ich gucke es mir an, aber finde da keinen Fehler.
Gibt es bei dir im ultimate-Ordner ein vio_stored_files/lotto Ordner mit jackpot.vio drin?

**Comment by KfzMatze45** [comment]
Die Datei ist im besagten Ordner und in der Datei steht eine Summer. 

Wenn du möchtest kannst du es dir gerne Mal um 15 Uhr per TeamViewer anschauen

**Comment by emre1702** [comment]
Versuch mal auf dem Server die Rechte zum User zu geben.
Vielleicht hast du einfach keine Rechte an dieser Datei.

**Comment by KfzMatze45** [comment]
Der Order hat Rechte, Und wirt auch mit gestartet. :D

**Comment by emre1702** [comment]
Naja, es scheint kein Script-Fehler zu sein.
